### ISSUE TITLE
Create new model: Document

### ISSUE THREAD

**Issue by am-webdev** [am-webdev/broker-models#7]
**Background**
```
Document extends BaseEntity
--------------
- string: type
- byte[]: content
- byte[32]: hash (sha-256)
```

**Tasks**

- [x] Create new Model
- [x] Define a new database scheme (documentId, as all other tables)
- [x] JPA mapping
- [ ] implement 2 Service methods
    - [ ] GET person/{:identity}/avatar (response: content+mimetype)
    - [x] PUT person/{:identity}/avatar (check if hash does already exist.)
- [x] Add FK to Person: to "avatar": relation: 0..1 - n  
- [x] Adjust model Person:
    - [x] get()
    - [x] set() (allows null)
- [ ] Tests?

**Definition of Done**
The new model is implemented and database stores resources within a new scheme.
